### PR TITLE
Fix theme

### LINKED ISSUE #7: Example often highlights the wrong heading.
For some sections the wrong sidebar entries are highlighted. For example https://jorel.dev/mdBook-pagetoc/chapter_2.html#apricot stays on `orange`.

Tested with Chrome and Firefox latest.

### PR DESCRIPTION
**Pull request by deemp**
- Update theme (fix #7, #10)
- Update README
- Map content sections to an active TOC element (see [example](https://deemp.github.io/mdBook-pagetoc/chapter_2.html))

### CODE REVIEW

**Comment by JorelAli** [comment]
I'm not particularly keen on this PR - it seems to step very far away from the original core design concepts that mdBook-pagetoc aimed to deliver from the beginning. In the [original issue](https://github.com/rust-lang/mdBook/issues/1263), the examples of other documentation systems that have a page table of contents are able to:

- Keep the main content visible in the center of the screen
- Not draw too much attention from the reader by making the table of contents small in size.

In the current implementation of this, we maintain the position of the main document in the center of the screen for easy reading and to not change the main layout of mdBook in general. We also have smaller text (all of the same size) to not distract readers from the main content. To differentiate heading levels, we make use of indentation:

image

However, in your implementation the content is pushed to the left and is no longer center-aligned in the browser window:

image

I think your implementation's text formatting is far too large and it poses a considerable distraction to readers. The use of larger text for different chapter sections is unnecessary, because indentation already indicates the hierarchy of the document's structure:

image

**Comment by deemp** [comment]
> I think your implementation's text formatting is far too large and it poses a considerable distraction to readers. The use of larger text for different chapter sections is unnecessary, because indentation already indicates the hierarchy of the document's structure.

OK, agree. Just wanted to check.

> Not draw too much attention from the reader by making the table of contents small in size.

I think its size should be adjustable so that people can decide what size is OK.

> However, in your implementation the content is pushed to the left and is no longer center-aligned in the browser window.

My implementation tries to overcome #10 when sidebar is visible.

image

In your version,  the page looks like this.

image

**Comment by deemp** [comment]
@JorelAli, found a solution. See [here](https://deemp.github.io/mdBook-pagetoc/chapter_2.html)


In small windows, I center text + TOC.

sidebar visible
image

sidebar hidden
image


In bigger windows, I center text only.

sidebar visible
image


sidebar hidden
image

**Comment by deemp** [comment]
@JorelAli, what do you think about this compromise?

**Comment by JorelAli** [comment]
Apologies for the delay, yes, this is a suitable compromise and I'm happy to go with this.

**Pull request merged**
